### ISSUE TITLE
Dynamic Sidebar

### ISSUE THREAD

**Issue by btd1337** [mika-el/angular-admin-lte#4]
It's possible to create a dynamic sidebar links?

**Comment by mika-el** [comment]
Hi,

Yes you can update dynamically the sidebar left menu.
Modify the menu and send it to layout.setSidebarLeftMenu(menu). 
Look here https://mika-el.github.io/angular-admin-lte/#/layout/configuration

**Comment by rey-coder** [comment]
Hi, I have dynamic links done as above, the issue faced is opening nested children i.e The first level opens the children links, then clicking on a child link (that has more children) closes all the child links instead of further opening the nested child links.

for instance 

```
sidebarLeftMenu: [
  {label: 'MAIN NAVIGATION', separator: true},
  {label: 'Start', route: '/', iconClasses: 'fa fa-th'},
  {label: 'Parent', iconClasses: 'fa fa-files-o', children: [
    {label: 'Children', route: 'parent/children'},
    {label: 'Parent 2', children: [
      {label: 'Children 2', route: 'parent/parent2/children2'}
    ]}
    ...
  ]}
]
```

clicking "Parent" will show the child links i.e "Parent 2" while clicking "Parent 2" will instead hide "Parent 2" rather than display child links i.e. "Children 2".

I am not sure if it's an issue with the library or how I am doing it since there are no errors in web & angular console.

Thanks!

**Comment by MRDcoder** [comment]
same issue, please guide to use for multilevel menu
